# Generated by Django 5.1.1 on 2024-10-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_internship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Internship",
        ),
    ]
