# Generated by Django 5.1.1 on 2024-10-09 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0006_alter_stageprogress_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
