# Generated by Django 5.1.1 on 2024-10-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0008_materialprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialprogress",
            name="stage_progress",
        ),
    ]
