# Generated by Django 5.1.1 on 2024-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0009_remove_materialprogress_stage_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialprogress",
            name="confirmation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialprogress",
            name="mentor_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="materialprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Не пройден"),
                    ("pending", "Ожидание"),
                    ("completed", "Завершен"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
