# Generated by Django 5.1.1 on 2024-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="required_questions",
            field=models.IntegerField(default=5),
        ),
    ]
