# Generated by Django 5.1.1 on 2024-10-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_test_required_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="passing_score",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "Один верный ответ"),
                    ("multiple", "Несколько верных ответов"),
                    ("true_false", "Верно/Неверно"),
                    ("sequence", "Последовательность"),
                    ("match", "Соответствие"),
                ],
                max_length=20,
            ),
        ),
    ]
