# Generated by Django 5.1.1 on 2024-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_test_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="correct_answers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testresult",
            name="total_questions_count",
            field=models.IntegerField(default=0),
        ),
    ]
