# Generated by Django 5.1.1 on 2024-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_position_duration_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="stages_count",
            field=models.IntegerField(default=1),
        ),
    ]
